### ISSUE TITLE
Breaks in apps with Fastboot

### ISSUE THREAD

**Issue by vlascik** [siva-sundar/ember-template-inspector#19]
Addon breaks apps with Fastboot. As far as I can tell, it uses DOM document object, which doesn't exist in Fastboot, addon doesn't do any checks for it.

To reproduce the problem it should be enough to run the app after `ember install ember-cli-fastboot`

**Comment by siva-sundar** [comment]
@vlascik Thanks for reporting.

Will look into it. Until then kindly use https://github.com/siva-sundar/ember-template-inspector/releases/tag/v0.0.6

**Comment by siva-sundar** [comment]
@vlascik Could you please share your package.json for better clarity ?

**Comment by siva-sundar** [comment]
@vlascik Sorry for the inconvenience.

Re-opening this issue.

**Comment by siva-sundar** [comment]
Fixed in https://github.com/siva-sundar/ember-template-inspector/pull/34
